import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Indicador from '#models/indicador'
import Proceso from '#models/proceso'

export default class extends BaseSeeder {
  async run() {
    // Obtener todos los procesos para mapear por nombre
    const procesos = await Proceso.all()
    const getProcesoId = (nombre: string) => {
      const proceso = procesos.find((p) =>
        p.nombre.toLowerCase().includes(nombre.toLowerCase()) ||
        nombre.toLowerCase().includes(p.nombre.toLowerCase())
      )
      return proceso ? proceso.id : 1
    }

    const indicadores = [
      // ========== DIRECCIONAMIENTO ==========
      {
        codigo: 'IND-DIR-001',
        procesoId: getProcesoId('Planeacion Estrategica'),
        nombre: 'Cumplimiento de Objetivos Estrategicos',
        formula: '(Objetivos cumplidos / Objetivos planteados) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '≥90%',
        responsable: 'Gerente General',
        orden: 1,
      },
      {
        codigo: 'IND-DIR-002',
        procesoId: getProcesoId('Planeacion Estrategica'),
        nombre: 'Ejecucion Presupuestal',
        formula: '(Presupuesto ejecutado / Presupuesto asignado) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficiencia' as const,
        meta: '≥85%',
        responsable: 'Gerente General',
        orden: 2,
      },
      {
        codigo: 'IND-DIR-003',
        procesoId: getProcesoId('Gestion de Riesgos'),
        nombre: 'Gestion de Riesgos',
        formula: '(Riesgos mitigados / Riesgos identificados) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '≥80%',
        responsable: 'Lider de Calidad',
        orden: 3,
      },
      {
        codigo: 'IND-DIR-004',
        procesoId: getProcesoId('Gestion de Soluciones IA'),
        nombre: 'Efectividad de Soluciones IA',
        formula: '(Soluciones IA exitosas / Total soluciones IA) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '≥85%',
        responsable: 'Lider de IA',
        orden: 4,
      },

      // ========== INGENIERIA ==========
      {
        codigo: 'IND-ING-001',
        procesoId: getProcesoId('Ejecucion y Control'),
        nombre: 'Cumplimiento de Dailies',
        formula: '(Dailies ejecutados / Dailies programados) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥95%',
        responsable: 'Lider de Proyecto',
        orden: 1,
      },
      {
        codigo: 'IND-ING-002',
        procesoId: getProcesoId('Ejecucion y Control'),
        nombre: 'Deteccion Oportuna de Desviaciones',
        formula: '(Desviaciones detectadas en sprint / Total desviaciones) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Por Sprint',
        tipo: 'Eficacia' as const,
        meta: '≥90%',
        responsable: 'Lider de Proyecto',
        orden: 2,
      },
      {
        codigo: 'IND-ING-003',
        procesoId: getProcesoId('Ejecucion y Control'),
        nombre: 'Variacion de Costo (CPI)',
        formula: 'CPI = EV / AC (Valor Ganado / Costo Real)',
        unidad: 'Indice',
        frecuencia: 'Mensual',
        tipo: 'Eficiencia' as const,
        meta: '≥1.0',
        responsable: 'Lider de Proyecto',
        orden: 3,
      },
      {
        codigo: 'IND-ING-004',
        procesoId: getProcesoId('Ejecucion y Control'),
        nombre: 'Variacion de Cronograma (SPI)',
        formula: 'SPI = EV / PV (Valor Ganado / Valor Planificado)',
        unidad: 'Indice',
        frecuencia: 'Mensual',
        tipo: 'Eficiencia' as const,
        meta: '≥1.0',
        responsable: 'Lider de Proyecto',
        orden: 4,
      },
      {
        codigo: 'IND-ING-005',
        procesoId: getProcesoId('Ejecucion y Control'),
        nombre: 'Cierre de Acciones Correctivas',
        formula: '(Acciones cerradas a tiempo / Total acciones) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥90%',
        responsable: 'Lider de Proyecto',
        orden: 5,
      },
      {
        codigo: 'IND-ING-006',
        procesoId: getProcesoId('Ejecucion y Control'),
        nombre: 'Satisfaccion del Cliente (NPS)',
        formula: '% Promotores - % Detractores',
        unidad: 'Indice NPS',
        frecuencia: 'Por Proyecto',
        tipo: 'Eficacia' as const,
        meta: '≥50',
        responsable: 'Lider de Proyecto',
        orden: 6,
      },
      {
        codigo: 'IND-ING-007',
        procesoId: getProcesoId('Ejecucion y Control'),
        nombre: 'Uso de Claude IA en Reportes',
        formula: '(Reportes con IA / Total reportes) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficiencia' as const,
        meta: '≥70%',
        responsable: 'Lider de Proyecto',
        orden: 7,
      },
      {
        codigo: 'IND-ING-008',
        procesoId: getProcesoId('Ejecucion y Control'),
        nombre: 'Documentacion de Lecciones Aprendidas',
        formula: '(Lecciones documentadas / Proyectos cerrados) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Por Proyecto',
        tipo: 'Eficacia' as const,
        meta: '100%',
        responsable: 'Lider de Proyecto',
        orden: 8,
      },
      {
        codigo: 'IND-ING-009',
        procesoId: getProcesoId('Arquitectura'),
        nombre: 'Tasa de Defectos Arquitectonicos',
        formula: '(Defectos arquitectonicos / Total defectos) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Por Release',
        tipo: 'Calidad' as const,
        meta: '≤5%',
        responsable: 'Arquitecto de Software',
        orden: 9,
      },
      {
        codigo: 'IND-ING-010',
        procesoId: getProcesoId('Arquitectura'),
        nombre: 'Cumplimiento Plazos Arquitectura',
        formula: '(Entregas a tiempo / Total entregas) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥90%',
        responsable: 'Arquitecto de Software',
        orden: 10,
      },
      {
        codigo: 'IND-ING-011',
        procesoId: getProcesoId('Calidad de Software'),
        nombre: 'Porcentaje de Historias Probadas Oportunamente',
        formula: '(Historias probadas en sprint / Total historias) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Por Sprint',
        tipo: 'Eficacia' as const,
        meta: '≥95%',
        responsable: 'Lider de QA',
        orden: 11,
      },
      {
        codigo: 'IND-ING-012',
        procesoId: getProcesoId('Calidad de Software'),
        nombre: 'Defectos Detectados en Produccion',
        formula: 'Cantidad de defectos reportados en produccion',
        unidad: 'Numero',
        frecuencia: 'Mensual',
        tipo: 'Calidad' as const,
        meta: '≤3',
        responsable: 'Lider de QA',
        orden: 12,
      },
      {
        codigo: 'IND-ING-013',
        procesoId: getProcesoId('Calidad de Software'),
        nombre: 'Efectividad de Deteccion de Defectos',
        formula: '(Defectos QA / Total defectos) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficiencia' as const,
        meta: '≥90%',
        responsable: 'Lider de QA',
        orden: 13,
      },
      {
        codigo: 'IND-ING-014',
        procesoId: getProcesoId('Ingenieria de Requisitos'),
        nombre: 'Cobertura de Requisitos',
        formula: '(Requisitos implementados / Requisitos definidos) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Por Release',
        tipo: 'Eficacia' as const,
        meta: '100%',
        responsable: 'Analista de Requisitos',
        orden: 14,
      },
      {
        codigo: 'IND-ING-015',
        procesoId: getProcesoId('Planeacion de Proyectos'),
        nombre: 'Cumplimiento del Plan de Proyecto',
        formula: '(Actividades completadas / Actividades planificadas) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥90%',
        responsable: 'Lider de Proyecto',
        orden: 15,
      },
      {
        codigo: 'IND-ING-016',
        procesoId: getProcesoId('Mesa de Soporte'),
        nombre: 'Tiempo de Resolucion Mesa de Soporte',
        formula: '(Tickets resueltos en SLA / Total tickets) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥90%',
        responsable: 'Lider de Soporte',
        orden: 16,
      },
      {
        codigo: 'IND-ING-017',
        procesoId: getProcesoId('Mesa de Soporte'),
        nombre: 'Satisfaccion del Usuario en Soporte',
        formula: 'Promedio calificacion encuestas de satisfaccion',
        unidad: 'Escala 1-5',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥4.5',
        responsable: 'Lider de Soporte',
        orden: 17,
      },
      {
        codigo: 'IND-ING-018',
        procesoId: getProcesoId('Desarrollo de Software'),
        nombre: 'Densidad de Defectos en Codigo',
        formula: 'Defectos / KLOC (Miles de lineas de codigo)',
        unidad: 'Defectos/KLOC',
        frecuencia: 'Por Release',
        tipo: 'Calidad' as const,
        meta: '≤5',
        responsable: 'Lider Tecnico',
        orden: 18,
      },
      {
        codigo: 'IND-ING-019',
        procesoId: getProcesoId('Desarrollo de Software'),
        nombre: 'Cobertura de Pruebas Automatizadas',
        formula: '(Lineas cubiertas / Total lineas) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Por Sprint',
        tipo: 'Eficiencia' as const,
        meta: '≥80%',
        responsable: 'Lider de QA',
        orden: 19,
      },

      // ========== COMERCIAL ==========
      {
        codigo: 'IND-COM-001',
        procesoId: getProcesoId('Planeacion y Generacion de Demanda'),
        nombre: 'Tasa de Conversion de Leads',
        formula: '(Leads convertidos / Total leads) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥20%',
        responsable: 'Director Comercial',
        orden: 1,
      },
      {
        codigo: 'IND-COM-002',
        procesoId: getProcesoId('Planeacion y Generacion de Demanda'),
        nombre: 'Cumplimiento Meta de Ventas',
        formula: '(Ventas realizadas / Meta de ventas) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥90%',
        responsable: 'Director Comercial',
        orden: 2,
      },
      {
        codigo: 'IND-COM-003',
        procesoId: getProcesoId('Gestion PQRS'),
        nombre: 'Tiempo de Respuesta a PQRS',
        formula: '(PQRS respondidas en tiempo / Total PQRS) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥95%',
        responsable: 'Analista de Servicio',
        orden: 3,
      },
      {
        codigo: 'IND-COM-004',
        procesoId: getProcesoId('Gestion PQRS'),
        nombre: 'Indice de Satisfaccion del Cliente',
        formula: 'Promedio calificacion encuestas de satisfaccion',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '≥90%',
        responsable: 'Director Comercial',
        orden: 4,
      },
      {
        codigo: 'IND-COM-005',
        procesoId: getProcesoId('Gestion PQRS'),
        nombre: 'Tasa de Retencion de Clientes',
        formula: '(Clientes activos periodo / Clientes inicio) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '≥85%',
        responsable: 'Director Comercial',
        orden: 5,
      },

      // ========== CONSULTORIA ==========
      {
        codigo: 'IND-CON-001',
        procesoId: getProcesoId('Planeacion del Servicio'),
        nombre: 'Cumplimiento de Entregas',
        formula: '(Entregas a tiempo / Total entregas) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥95%',
        responsable: 'Lider de Consultoria',
        orden: 1,
      },
      {
        codigo: 'IND-CON-002',
        procesoId: getProcesoId('Planeacion del Servicio'),
        nombre: 'Horas Facturadas vs Planificadas',
        formula: '(Horas facturadas / Horas planificadas) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥90%',
        responsable: 'Lider de Consultoria',
        orden: 2,
      },
      {
        codigo: 'IND-CON-003',
        procesoId: getProcesoId('Ejecucion Consultoria'),
        nombre: 'Satisfaccion del Cliente Consultoria',
        formula: 'Promedio calificacion encuestas post-servicio',
        unidad: 'Escala 1-5',
        frecuencia: 'Por Proyecto',
        tipo: 'Eficacia' as const,
        meta: '≥4.5',
        responsable: 'Lider de Consultoria',
        orden: 3,
      },
      {
        codigo: 'IND-CON-004',
        procesoId: getProcesoId('Ejecucion Consultoria'),
        nombre: 'Rentabilidad por Proyecto',
        formula: '(Ingresos - Costos) / Ingresos × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Por Proyecto',
        tipo: 'Eficiencia' as const,
        meta: '≥30%',
        responsable: 'Lider de Consultoria',
        orden: 4,
      },
      {
        codigo: 'IND-CON-005',
        procesoId: getProcesoId('Ejecucion Consultoria'),
        nombre: 'Efectividad de Recomendaciones',
        formula: '(Recomendaciones implementadas / Total recomendaciones) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '≥80%',
        responsable: 'Lider de Consultoria',
        orden: 5,
      },

      // ========== TALENTO HUMANO ==========
      {
        codigo: 'IND-TH-001',
        procesoId: getProcesoId('Induccion'),
        nombre: 'Cobertura de Induccion',
        formula: '(Personal que completo induccion / Total personal nuevo) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '100%',
        responsable: 'Lider de Talento Humano',
        orden: 1,
      },
      {
        codigo: 'IND-TH-002',
        procesoId: getProcesoId('Induccion'),
        nombre: 'Nivel de Aprobacion Induccion',
        formula: '(Evaluaciones aprobadas ≥80% / Total evaluaciones) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥95%',
        responsable: 'Lider de Talento Humano',
        orden: 2,
      },
      {
        codigo: 'IND-TH-003',
        procesoId: getProcesoId('Induccion'),
        nombre: 'Tiempo Promedio de Induccion',
        formula: 'Σ(Tiempo total por empleado) / Total empleados',
        unidad: 'Horas',
        frecuencia: 'Mensual',
        tipo: 'Eficiencia' as const,
        meta: '≤40 horas',
        responsable: 'Lider de Talento Humano',
        orden: 3,
      },
      {
        codigo: 'IND-TH-004',
        procesoId: getProcesoId('SST'),
        nombre: 'Indice de Frecuencia de Accidentes',
        formula: '(N° Accidentes / Horas Hombre Trabajadas) × 1,000,000',
        unidad: 'Indice',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≤5',
        responsable: 'Analista de Procesos',
        orden: 4,
      },
      {
        codigo: 'IND-TH-005',
        procesoId: getProcesoId('SST'),
        nombre: 'Cumplimiento del Plan SST',
        formula: '(Actividades ejecutadas / Actividades programadas) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '≥90%',
        responsable: 'Analista de Procesos',
        orden: 5,
      },
      {
        codigo: 'IND-TH-006',
        procesoId: getProcesoId('SST'),
        nombre: 'Cobertura de Capacitaciones SST',
        formula: '(Personal capacitado / Total personal) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficiencia' as const,
        meta: '100%',
        responsable: 'Lider de Talento Humano',
        orden: 6,
      },
      {
        codigo: 'IND-TH-007',
        procesoId: getProcesoId('Gestion de Ingreso'),
        nombre: 'Tiempo de Contratacion',
        formula: '(Contrataciones en ≤30 dias / Total contrataciones) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥80%',
        responsable: 'Lider TH',
        orden: 7,
      },
      {
        codigo: 'IND-TH-008',
        procesoId: getProcesoId('Gestion de Ingreso'),
        nombre: 'Retencion Post-Periodo Prueba',
        formula: '(Aprobaron periodo prueba / Total contratados) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficiencia' as const,
        meta: '≥90%',
        responsable: 'Analista TH',
        orden: 8,
      },
      {
        codigo: 'IND-TH-009',
        procesoId: getProcesoId('Gestion de Ingreso'),
        nombre: 'Efectividad IA Preseleccion',
        formula: '(Preseleccionados IA que avanzan / Total preseleccionados IA) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficiencia' as const,
        meta: '≥70%',
        responsable: 'Analista TH',
        orden: 9,
      },
      {
        codigo: 'IND-TH-010',
        procesoId: getProcesoId('Bienestar'),
        nombre: 'Cobertura de Programas Bienestar',
        formula: '(Empleados participantes / Total empleados) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '≥80%',
        responsable: 'Lider de Talento Humano',
        orden: 10,
      },
      {
        codigo: 'IND-TH-011',
        procesoId: getProcesoId('Bienestar'),
        nombre: 'Satisfaccion con Programas Bienestar',
        formula: 'Promedio de calificacion en encuestas de satisfaccion',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '≥85%',
        responsable: 'Lider de Talento Humano',
        orden: 11,
      },
      {
        codigo: 'IND-TH-012',
        procesoId: getProcesoId('Bienestar'),
        nombre: 'Cumplimiento Presupuestal Bienestar',
        formula: '(Presupuesto ejecutado / Presupuesto asignado) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficiencia' as const,
        meta: '≥90%',
        responsable: 'Lider de Talento Humano',
        orden: 12,
      },
      {
        codigo: 'IND-TH-013',
        procesoId: getProcesoId('Comunicaciones Internas'),
        nombre: 'Alcance de Comunicaciones',
        formula: '(Empleados que reciben comunicacion / Total empleados) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '100%',
        responsable: 'Lider de Talento Humano',
        orden: 13,
      },
      {
        codigo: 'IND-TH-014',
        procesoId: getProcesoId('Comunicaciones Internas'),
        nombre: 'Tiempo de Respuesta Comunicaciones',
        formula: 'Tiempo promedio entre solicitud y publicacion',
        unidad: 'Dias',
        frecuencia: 'Mensual',
        tipo: 'Eficiencia' as const,
        meta: '≤2 dias',
        responsable: 'Analista de Procesos',
        orden: 14,
      },
      {
        codigo: 'IND-TH-015',
        procesoId: getProcesoId('Entrenamiento'),
        nombre: 'Cumplimiento Plan de Formacion',
        formula: '(Formaciones ejecutadas / Formaciones programadas) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '≥90%',
        responsable: 'Lider de Talento Humano',
        orden: 15,
      },
      {
        codigo: 'IND-TH-016',
        procesoId: getProcesoId('Entrenamiento'),
        nombre: 'Efectividad de la Formacion',
        formula: '(Evaluaciones aprobadas / Total evaluaciones) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '≥85%',
        responsable: 'Lider de Talento Humano',
        orden: 16,
      },
      {
        codigo: 'IND-TH-017',
        procesoId: getProcesoId('Entrenamiento'),
        nombre: 'Optimizacion Presupuesto Formacion',
        formula: '(Presupuesto ejecutado / Presupuesto asignado) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Semestral',
        tipo: 'Eficiencia' as const,
        meta: '≥85%',
        responsable: 'Lider de Talento Humano',
        orden: 17,
      },
      {
        codigo: 'IND-TH-018',
        procesoId: getProcesoId('Gestion del Desempeno'),
        nombre: 'Cumplimiento de Evaluaciones Desempeno',
        formula: '(Evaluaciones realizadas / Evaluaciones programadas) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '100%',
        responsable: 'Lider de Talento Humano',
        orden: 18,
      },
      {
        codigo: 'IND-TH-019',
        procesoId: getProcesoId('Gestion del Desempeno'),
        nombre: 'Efectividad Planes de Desarrollo',
        formula: '(Objetivos cumplidos / Objetivos planteados) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Semestral',
        tipo: 'Eficiencia' as const,
        meta: '≥80%',
        responsable: 'Lider de Talento Humano',
        orden: 19,
      },
      {
        codigo: 'IND-TH-020',
        procesoId: getProcesoId('Gestion del Desempeno'),
        nombre: 'Cobertura de Capacitacion',
        formula: '(Personal capacitado / Total personal) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Calidad' as const,
        meta: '≥90%',
        responsable: 'Lider de Talento Humano',
        orden: 20,
      },

      // ========== MEJORAMIENTO ==========
      {
        codigo: 'IND-MEJ-001',
        procesoId: getProcesoId('Gestion del Cambio'),
        nombre: 'Implementacion de Cambios',
        formula: '(Cambios implementados exitosamente / Total cambios) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥90%',
        responsable: 'Lider de Calidad',
        orden: 1,
      },
      {
        codigo: 'IND-MEJ-002',
        procesoId: getProcesoId('Mejoramiento Continuo'),
        nombre: 'Cierre de No Conformidades',
        formula: '(NC cerradas a tiempo / Total NC) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥95%',
        responsable: 'Lider de Calidad',
        orden: 2,
      },
      {
        codigo: 'IND-MEJ-003',
        procesoId: getProcesoId('Mejoramiento Continuo'),
        nombre: 'Efectividad de Acciones de Mejora',
        formula: '(Acciones efectivas / Total acciones implementadas) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '≥85%',
        responsable: 'Lider de Calidad',
        orden: 3,
      },

      // ========== PROCESOS ==========
      {
        codigo: 'IND-PRO-001',
        procesoId: getProcesoId('Auditorias'),
        nombre: 'Cumplimiento de Auditorias',
        formula: '(Auditorias realizadas / Auditorias programadas) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '100%',
        responsable: 'Auditor Interno',
        orden: 1,
      },
      {
        codigo: 'IND-PRO-002',
        procesoId: getProcesoId('Gestion Documental'),
        nombre: 'Cumplimiento Gestion Documental',
        formula: '(Documentos actualizados / Total documentos) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '≥95%',
        responsable: 'Lider de Calidad',
        orden: 2,
      },
      {
        codigo: 'IND-PRO-003',
        procesoId: getProcesoId('Medicion y Analisis'),
        nombre: 'Medicion y Analisis de Indicadores',
        formula: '(Indicadores medidos / Total indicadores) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Mensual',
        tipo: 'Eficacia' as const,
        meta: '100%',
        responsable: 'Analista de Procesos',
        orden: 3,
      },
      {
        codigo: 'IND-PRO-004',
        procesoId: getProcesoId('Aseguramiento de la Calidad'),
        nombre: 'Aseguramiento de Calidad',
        formula: '(Controles conformes / Total controles) × 100',
        unidad: 'Porcentaje',
        frecuencia: 'Trimestral',
        tipo: 'Eficacia' as const,
        meta: '≥95%',
        responsable: 'Lider de Calidad',
        orden: 4,
      },
    ]

    await Indicador.createMany(indicadores)
  }
}
